import json
import os
import subprocess
from pathlib import Path

from openai import OpenAI


TARGET_DIRECTORY = Path("vulnerable_app")
REPORT_DIRECTORY = Path("reports")

BANDIT_REPORT = REPORT_DIRECTORY / "bandit.json"
FINAL_REPORT = REPORT_DIRECTORY / "security_review.md"


def run_bandit():
    """
    Run Bandit against the target application and save
    the findings as JSON.
    """

    REPORT_DIRECTORY.mkdir(exist_ok=True)

    command = [
        "bandit",
        "-r",
        str(TARGET_DIRECTORY),
        "-f",
        "json",
        "-o",
        str(BANDIT_REPORT),
        "--exit-zero"
    ]

    print("[+] Running Bandit security scan...")

    subprocess.run(
        command,
        check=True
    )

    print(f"[+] Bandit report saved to {BANDIT_REPORT}")


def load_bandit_results():
    """
    Load Bandit's JSON report.
    """

    with open(BANDIT_REPORT, "r", encoding="utf-8") as file:
        data = json.load(file)

    return data.get("results", [])


def get_code_context(filename, line_number, radius=3):
    """
    Extract a few lines around the vulnerable line
    so the LLM can review the actual source code.
    """

    path = Path(filename)

    if not path.exists():
        return "Source code unavailable."

    lines = path.read_text(encoding="utf-8").splitlines()

    start = max(0, line_number - radius - 1)
    end = min(len(lines), line_number + radius)

    context = []

    for index in range(start, end):
        context.append(
            f"{index + 1}: {lines[index]}"
        )

    return "\n".join(context)


def prepare_findings(results):
    """
    Convert Bandit findings into a compact format
    for the LLM.
    """

    findings = []

    for finding in results:

        filename = finding.get("filename")
        line_number = finding.get("line_number")

        findings.append(
            {
                "test_id": finding.get("test_id"),
                "severity": finding.get("issue_severity"),
                "confidence": finding.get("issue_confidence"),
                "description": finding.get("issue_text"),
                "filename": filename,
                "line": line_number,
                "code": get_code_context(
                    filename,
                    line_number
                )
            }
        )

    return findings


def review_with_llm(findings):
    """
    Send static-analysis findings and application architecture
    to an LLM for secure code review and STRIDE threat modeling.
    """

    client = OpenAI()

    architecture = """
Application architecture:

User
  |
  v
Flask HTTP API
  |
  +-- /ping endpoint
  |       |
  |       v
  |   Operating System Command
  |
  +-- /calculate endpoint
  |
  +-- /profile endpoint
          |
          v
    Serialized User Data

The application also contains a Flask SECRET_KEY.
"""

    prompt = f"""
You are performing an application security review.

The following findings were generated by Bandit static analysis.

BANDIT FINDINGS:

{json.dumps(findings, indent=2)}

APPLICATION ARCHITECTURE:

{architecture}

Produce a concise professional security assessment in Markdown.

Create these sections:

# Executive Summary

Briefly explain the overall security posture.

# Secure Code Review

For every Bandit finding include:

- Vulnerability
- File and line
- Severity
- Why the code is insecure
- Realistic security impact
- Recommended remediation
- Safer code example

Do not invent source-code vulnerabilities that are not supported
by the supplied code or scanner findings.

# Threat Model

Use the STRIDE methodology.

Create a table containing:

| Component | STRIDE Category | Threat | Impact | Mitigation |

Identify approximately 5 relevant threats.

# Priority Remediation

List the three most important fixes in priority order.

Clearly distinguish static-analysis findings from threat-model risks.
"""

    print("[+] Sending findings to LLM...")

    response = client.responses.create(
        model=os.getenv("OPENAI_MODEL", "gpt-4.1"),
        input=prompt
    )

    return response.output_text


def save_report(report):
    FINAL_REPORT.write_text(
        report,
        encoding="utf-8"
    )

    print(
        f"[+] Final security report saved to {FINAL_REPORT}"
    )


def main():

    run_bandit()

    results = load_bandit_results()

    print(
        f"[+] {len(results)} Bandit findings detected"
    )

    findings = prepare_findings(results)

    report = review_with_llm(findings)

    save_report(report)

    print("[+] Security review completed")


if __name__ == "__main__":
    main()